Increase robustness of geojson parsing by allowing extra properties and null values
getodk/javarosa pull request #681
Opened 2022-05-04 22:18 UTC by lognaturel

Closes issues described on forum starting [here](https://forum.getodk.org/t/odk-collect-v2022-2-beta-select-from-map-geojson-datasets/36913/17?u=ln)

#### What has been done to verify that this works as intended?
Added tests based on forum reports.

#### Why is this the best possible solution? Were any other approaches considered?
I briefly considered using an `ObjectMapper` instead of the parser. But I do think it's better to be able to stream the parsing. I think this is much more robust but it's possible there are still cases I haven't thought of.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This does change the geojson parsing strategy quite a bit so there's risk. Our test coverage is good, though, so I don't think it's high.

#### Do we need any specific form for testing your changes? If so, please attach one.
See tests.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

2022-05-06 13:04 UTC, seadowg requested changes
As well as the inline comments:

* I do feel like the parsing feels a little "too close to the metal" here. Why not use a proper object mapper here?
* The `.geojson` example files would be a lot easier to read if they were formatted. You can add `.geojson` as a JSON file type in IntelliJ using [File type associations](https://www.jetbrains.com/help/idea/creating-and-registering-file-types.html) and then auto format the files.

2022-05-06 13:04 UTC, seadowg commented on src/test/resources/org/javarosa/core/model/instance/geojson/feature-collection-with-nulls.geojson
> +    "extra": null,
Why do we have a top level `"extra"` set to `null` here as well?

2022-05-06 13:04 UTC, seadowg commented on src/test/java/org/javarosa/core/model/instance/geojson/GeoJsonExternalInstanceTest.java
> +    public void parse_allowsNulls() throws IOException {
Probably best to be explicit that we mean null feature properties here.

2022-05-10 15:22 UTC, lognaturel commented
> Why not use a proper object mapper here?

Streaming means we don't have to have two in-memory representations of the file. These files can get big so it seems worth it. It also better matches the CSV implementation. More on that in the original PR (https://github.com/getodk/javarosa/pull/655). I'd rather keep this unless we have a really good reason not to.

> The .geojson example files would be a lot easier to read if they were formatted. 

I like the semantic formatting of those files. But you're right that it's annoying to have files that aren't auto formatted, fixed, thanks.

2022-05-10 18:10 UTC, merged