Use first repeat instance(s) for jr:choice-name choices
getodk/javarosa pull request #758
Opened 2024-04-12 22:20 UTC by lognaturel

Closes #757

#### What has been done to verify that this works as intended?
Added tests

#### Why is this the best possible solution? Were any other approaches considered?
My initial instinct was that using a reference to a repeat nodeset rather than a specific repeat instance to specify where choices should be taken from is a form design issue. But then I realized that a standards-compliant XPath engine would use the first repeat instance(s) when given a nodeset reference where it needs a single node reference. 

This doesn't work well with choice filters but I think that's ok because it also wouldn't have been possible before. My priority here is to ensure that XLSForms that used to work continue to work without modification.

My recommendation for writing these kinds of `choice-name` calls would be to make them relative from within the repeat instance rather than making it from outside. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This only affects `choice-name` calls given a reference parameter that is a nodeset reference. I think the case in the test is the only one in which this kind of reference would make sense. There's also the analogous nested case and that's why there's a for loop to qualify every unboud reference level.

#### Do we need any specific form for testing your changes? If so, please attach one.
https://docs.google.com/spreadsheets/d/1MZvF9ynsOdGMWeZF8YsjuoUK9E0t83LZMi5-RsBOEiI/edit#gid=1068911091

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

2024-04-12 22:21 UTC, lognaturel commented on src/main/java/org/javarosa/core/model/FormDef.java
> +import static java.util.Collections.emptyList;
I think I'm likely the one who messed up this order previously. 😬 My IDE should now enforce the order that's mostly consistent across existing files.

2024-04-12 22:21 UTC, lognaturel commented on src/test/java/org/javarosa/core/model/ChoiceNameTest.java
> +    @Test public void choiceNameCallWithIndexedRepeatAndStaticChoices_worksWithMultipleRepeats() throws IOException, XFormParser.ParseException {
This is not affected by the code change. It's there to document behavior that has always worked.

2024-05-20 15:07 UTC, seadowg requested changes

2024-05-20 15:07 UTC, seadowg commented on src/main/java/org/javarosa/core/model/FormDef.java
> +                                    // ref, the reference used to specify where choices are defined, could be an absolute
This `IFunctionHandler` implementation should be moved out to another file now we're touching it again.

2024-05-21 12:01 UTC, seadowg approved these changes

2024-05-21 14:11 UTC, merged