Add multi-argument distance variant
getodk/javarosa pull request #761
Opened 2024-05-10 19:13 UTC by lognaturel

Closes #740

#### What has been done to verify that this works as intended?
Added a test.

#### Why is this the best possible solution? Were any other approaches considered?
See https://github.com/getodk/xforms-spec/pull/311 for spec consideration. An alternative would be to always only allow a single arg but to allow that arg to be a literal string rather than only a nodeset. This feels less intuitive to me.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.
https://docs.google.com/spreadsheets/d/1Dv9lD33Bfqz4XqmTNMJXm4NK9Lw0TloKph1juU0Kins/edit#gid=1068911091

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
https://github.com/getodk/docs/issues/1795

2024-05-14 00:59 UTC, tiritea commented
>An alternative would be to always only allow a single arg but to allow that arg to be a literal string rather than only a nodeset.

it actually seems more intuitive to me that the (singular) argument to the existing XPath distance() function should be able to support either a node/nodeset (for example, containing a geotrace value), or a literal string of the same. Many functions behave this way...

2024-05-20 15:29 UTC, seadowg commented
Removing myself as a reviewer until we've merged https://github.com/getodk/xforms-spec/pull/311

2024-05-21 12:12 UTC, seadowg requested changes

2024-05-21 12:12 UTC, seadowg commented on src/test/java/org/javarosa/core/util/GeoDistanceTest.java
> +                    bind("/data/distance").type("decimal").calculate("distance(/data/point1, '38.25021274773806 21.756382658677467 0 0', /data/point3, /data/point4, /data/point5)")
I'm guessing "point 2" is not pulled from a node to test that literals work fine here? I think if that's a concern it should move out to a separate test (or maybe a unit test of `XPathFuncExpr`) so it's not hidden in here.

2024-05-21 15:49 UTC, seadowg approved these changes

2024-05-21 17:22 UTC, merged